# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 93caa6a80df5c7df4affd1ca1c14a2ee358f049dbd0be94f192b8c2ca64e7e3b4c1a940abdb80613aedda9d98de87ce68e4889da864c595df633d8da64237c38 
  s3_access_key_id: <%= ENV["s3_access_key_id"] %>
  s3_secret: <%= ENV["s3_secret"] %>
  s3_bucket: datinggo
  s3_region: eu-east-1


test:
  secret_key_base: cacd12b074b25f627061ea678a1233d4e081443ff0dde0832ae3f6caf7f4eeaab126fc7aec52d111a4226fa1b7f0f94a87d29d3dfd12819082a5367053890d38
  s3_access_key_id: <%= ENV["s3_access_key_id"] %>
  s3_secret: <%= ENV["s3_secret"] %>
  s3_bucket: datinggo
  s3_region: eu-east-1
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  s3_access_key_id: <%= ENV["s3_access_key_id"] %>
  s3_secret: <%= ENV["s3_secret"] %>
  s3_bucket: datinggo
  s3_region: eu-east-1
